spring.application.name=JAWS-back

# DB 접속 주소
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT 설정
jwt.secret=jaws-secret-key-must-be-at-least-32-characters-long
jwt.access-token-expiration=86400000
jwt.refresh-token-expiration=604800000

# CORS 설정
cors.allowed-origins=http://localhost:3000

springdoc.swagger-ui.url=/swagger.yml
springdoc.swagger-ui.path=/swagger-ui.html vt 